name: STR-modelling
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pandas
  - numpy
  - jupyterlab
  - matplotlib
  - seaborn
  - scikit-learn
  - geopandas
  - folium
  - shapely